CREATE TABLE IF NOT EXISTS "user"
(
    id    bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    email VARCHAR(512),
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS "item"
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id    bigint,
    name        VARCHAR(255),
    description text,
    available   bool,
    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT fk_owner FOREIGN KEY (owner_id) REFERENCES "user" (id)
);

CREATE TABLE IF NOT EXISTS "comment"
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      bigint,
    item_id      bigint,
    description text,
    created TIMESTAMP ,
    CONSTRAINT pk_review PRIMARY KEY (id),
    CONSTRAINT fk_review_user FOREIGN KEY (user_id) REFERENCES "user" (id),
    CONSTRAINT fk_review_item FOREIGN KEY (item_id) REFERENCES "item" (id)
);

CREATE TABLE IF NOT EXISTS "booking"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_id    BIGINT      NOT NULL,
    booker_id  BIGINT      NOT NULL,
    start_date TIMESTAMP   NOT NULL,
    end_date   TIMESTAMP   NOT NULL,
    status     VARCHAR(50) NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (id),
    CONSTRAINT fk_item   FOREIGN KEY (item_id)   REFERENCES "item" (id),
    CONSTRAINT fk_booker FOREIGN KEY (booker_id) REFERENCES "user" (id)
);

