CREATE TABLE IF NOT EXISTS "user"
(
    id    bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    email VARCHAR(512),
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS "item"
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id    bigint,
    name        VARCHAR(255),
    description text,
    available   bool,
    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT fk_owner FOREIGN KEY (owner_id) REFERENCES "user" (id)
);

CREATE TABLE IF NOT EXISTS "comment"
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    userId      bigint,
    itemId      bigint,
    rating      smallint,
    description text,
    CONSTRAINT pk_review PRIMARY KEY (id),
    CONSTRAINT fk_review_user FOREIGN KEY (userId) REFERENCES "user" (id),
    CONSTRAINT fk_review_item FOREIGN KEY (itemId) REFERENCES "item" (id)
);

CREATE TABLE "booking"
(
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    item_id    BIGINT      NOT NULL,
    booker_id  BIGINT      NOT NULL,
    start_date TIMESTAMP   NOT NULL,
    end_date   TIMESTAMP   NOT NULL,
    status     VARCHAR(50) NOT NULL,
    CONSTRAINT fk_item   FOREIGN KEY (item_id)   REFERENCES "item" (id),
    CONSTRAINT fk_booker FOREIGN KEY (booker_id) REFERENCES "user" (id)
);

